name: influencer_recommender
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  auto_size_text: ^1.0.0
  shared_preferences: ^0.5.1+2
  flutter_twitter_login: ^1.1.0
  twitter: ^1.0.0
  scoped_model: ^1.0.1
  flare_flutter: ^1.3.4
  autocomplete_textfield: ^1.6.4



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/pics/header.jpg
   - assets/pics/header2.jpg
   - assets/pics/header3.jpg
   - assets/pics/header4.jpg
   - assets/pics/header5.jpg
   - assets/pics/categories/arts_entertainment.png
   - assets/pics/categories/automotive.png
   - assets/pics/categories/business.png
   - assets/pics/categories/careers.png
   - assets/pics/categories/education.png
   - assets/pics/categories/family_parenting.png
   - assets/pics/categories/food_drink.png
   - assets/pics/categories/health_fitness.png
   - assets/pics/categories/hobbies_interests.png
   - assets/pics/categories/home_garden.png
   - assets/pics/categories/illegal_content.png
   - assets/pics/categories/law_politics.png
   - assets/pics/categories/news.png
   - assets/pics/categories/personal_finance.png
   - assets/pics/categories/pets.png
   - assets/pics/categories/real_estate.png
   - assets/pics/categories/science.png
   - assets/pics/categories/shopping.png
   - assets/pics/categories/society.png
   - assets/pics/categories/sports.png
   - assets/pics/categories/style_fashion.png
   - assets/pics/categories/technology_computing.png
   - assets/pics/categories/travel.png

   - assets/pics/twiiter_background2.jpg
   - assets/flare/intro.flr

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
